services:
  db:
    container_name: odoo_db
    image: postgres:11
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  odoo13:
    container_name: odoo_service
    image: odoo:13
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    #command: odoo -u all -d testdb #Uncomment once db is initiated to automatically update modules after docker compose up -d